### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by jtourkos**
Adds unit tests for all handlers.

Re https://github.com/radicle-dev/drips-subgraph/issues/10

### CODE REVIEW

**Comment by gh0stwheel** [comment]
I tried to follow the instructions in DEVELOPMENT.md, but ran into errors. See the attached screenshot. Any ideas?

Screenshot 2023-03-10 at 8 09 41 AM

**Comment by gh0stwheel** [comment]
(I did check that graph-cli is installed by running `npm i -g @graphprotocol/graph-cli`)

**Comment by jtourkos** [comment]
Hmm, weird. Could you remove `node_modules` and `package-lock.json`, then `npm i` and retry?
"It works fine on my machine" 😅

**Comment by gh0stwheel** [comment]
Hmmm.... just tried it. I'm still getting the same errors. Any other ideas?

**Comment by jtourkos** [comment]
@gh0stwheel Let's have a quick call tomorrow to see what's happening. Curious if @efstajas has the same issue when building?

**Comment by efstajas** [comment]
I'm having the exact same issue too.

**Comment by jtourkos** [comment]
Alright, I managed to reproduce it. It should be OK now. Give it a try and let me know! 😊
@gh0stwheel  @efstajas

**Review by gh0stwheel — APPROVED** [review]
Looks good!

**Pull request merged**
